### PR TITLE
more meteor aliases

### PR DESCRIPTION
**Pull request by HyperSkys**
aliases

### CODE REVIEW

**Comment by iusemeteor** [comment]
the obsession is crazy ngl

**Comment by iusemeteor** [comment]
the only commits you made was different aliases (which you would know because you're fanboying me) which also doesnt prove im a skid LOL

**Comment by HyperSkys** [comment]
> the only commits you made was different aliases (which you would know because you're fanboying me) which also doesnt prove im a skid LOL

ur the one stalking my github lmao, what kinda logic u got skiddo?

**Comment by HyperSkys** [comment]
> why wouldn't I comment on the repo? it's the only form of communication since you've blocked me on all my alts 😹

??? u have me blocked now i tried unblocking u and adding u but u insta blocked me

**Comment by iusemeteor** [comment]
buddy I have blocked you because you kept block messaging. the fuck nigga?

**Pull request merged**
